### ISSUE TITLE
Tabplot package

### ISSUE THREAD

**Issue by jab57** [mtennekes/tabplot#19]
I am having an issue that I have not been able to find out any tracks to solve it.  I am trying to use package just based on the diamonds data set example and get the following error. 
Error in if (by < 1) stop("'by' must be > 0") : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In chunk.default(from = 1L, to = 53940L, by = c(double = 23058430092136940),  :
  NAs introduced by coercion to integer range

I used the package last year successfully but for some reason I cannot get it to work now.  Appreciate your help.

Thanks,

JAB

**Comment by jab57** [comment]
Here is some information on my R configuration.
Thanks,
jab57
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by mtennekes** [comment]
Could you provide a reproducible example?

**Comment by jab57** [comment]
Just noticed there was a closed item that suggested adding the following and it works.

options(ffbatchbytes = 1024^2 * 128) # 128 MB
options(ffmaxbytes = 1024^2 * 128 * 32) # 4096 MB

**Comment by jab57** [comment]
I just closed the incident as I was able to find a solution based on previous closed issue.

Thanks,

jab57
