### ISSUE TITLE
latest tabplot INSTALL problem zero exit status - (used to install ok in the past)

### ISSUE THREAD

**Issue by sfd99** [mtennekes/tabplot#22]
**_Hi Martijn!_**

Used your GREAT **tabplot** pkg
in the past. 
_Loved it! Excellent!_

Tried to install  
in latest Rstudio, 
but now get:

**> install_github("mtennekes/tabplot")**
...
** byte-compile and prepare package for lazy loading
Error: object ‘clone’ is not exported by 'namespace:ff'
Execution halted
ERROR: lazy loading failed for package ‘tabplot’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/4.0/tabplot’
Error: Failed to install 'tabplot' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpSM4sW4/file21ef6e32da6/tabplot_1.3-4.tar.gz’ 
had non-zero exit status

Help Martijn!  
(or anyone who can rescue the installation of this truly great pkg!).
Used to install & work **perfectly** in the past....

**SFD99
San Francisco
R 4.0.3
Rstudio 1.3.1073
Ubuntu Linux 20.04 64-bit.**

**Comment by sfd99** [comment]
**UPDATE Oc 25 202**0

Just updated pkg **ffbase** 
to latest version, (released today!).
**ffbase** installed ok.

Then tried installing **tabplopt** _again_.
Unfortunately, 
same error messages as before...(see above).

Help! Anyone...?.
**SFD99
San Francisco
R 4.0.3
Rstudio 1.3.1073
Ubuntu Linux 20.04 64-bit.**

**Comment by RobertSellers** [comment]
Same problem here.

**Comment by cfholbert** [comment]
I revised the code and recompiled. It works fine after installing bit_1.1-15.2, ff_2.2-14.2, and ffbase_0.12.8.

**Comment by sfd99** [comment]
**Hi Martijn!**

Could you **_please_** tell us
_step by step_,
how to install the new, working **tabplot**?.
And any previous packages needed ?.

**Installed pkgs:**
 - ffbase   0.13.1
 - ff           4.0.4
 - bit          4.0.4      

but  still get the **tabplot** installation error: 

> devtools::install_github("mtennekes/tabplot")
Downloading GitHub repo mtennekes/tabplot@HEAD
✓  checking for file ‘/tmp/RtmpeKnvPL/remotes3ef3639ab253/mtennekes-tabplot-977d218/DESCRIPTION’ ...
─  preparing ‘tabplot’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘tabplot_1.3-4.tar.gz’
   
Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘tabplot’ ...
** using staged installation
** R
** demo
** byte-compile and prepare package for lazy loading
Error: object ‘clone’ is not exported by 'namespace:ff'
Execution halted
ERROR: lazy loading failed for package ‘tabplot’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/4.0/tabplot’
Error: Failed to install 'tabplot' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpeKnvPL/file3ef36148b65/tabplot_1.3-4.tar.gz’ had non-zero exit status

_Help, Martijn!_
We _really_ want to get **tabplot** up and running.
It worked so great in the past...

**SFD99
San Francisco
R 4.0.4
Rstudio 1.4.1103
Ubuntu Linux 20.04 64-bit.**

**Comment by mtennekes** [comment]
I'm happy to submit the package to CRAN again, but I don't know anything about the internals and dependencies of `ff` and `ffbase`. 

@cfholbert and @edwindj could you take a look? If it all works fine, then I'll resubmit the package to CRAN.

**Comment by cfholbert** [comment]
@mtennekes there are still inconsistencies between the new version of ff and ffbase. I had to install older versions of these packages to get tabplot working. So, I don't think you should try submitting yet. Let me see if I can get tabplot working with the new versions of ff and ffbase.

**Comment by mtennekes** [comment]
@cfholbert That would be awesome!

**Comment by edwindj** [comment]
That would be nice: I will look at the problems this afternoon

**Comment by edwindj** [comment]
`ff` changed a couple of exported function, which were used by `tabplot`. Walking through the changes, but also thinking of offering an option to create table plots without `ff`, e.g. with data.table

**Comment by edwindj** [comment]
I fixed the issue with ff and ffbase. 
Long story short: 
- the ff package changed its function interface: a two or three functions were not exported anymore.
- the function `ffbase::binned_sum` stopped working whenever an extra argument `INDEX=NULL` was given. This has been fixed in `ffbase` version 0.13.2 (on its way to CRAN).
-

**Comment by sfd99** [comment]
THANKS
for the effective fix
to **ffbase**. 

The great **tabpolot** PKG 
now finally installs and works again!.

**Edwin -**
would a statue of you in downtown San Francisco
be acceptable ?.
(you deserve it 100%!).

**Q** (if I may):
when running the tabplot Fx:
   **itableplot()** ,
the Shiny app opens ok,
but w/ a red message: 
    "Error: could not find function "table**P**lot"
(seems to call the tableplot() Fx, 
 but w/ an uppercase "P" letter?...).

Maybe **@mtennekes** or you, Edwin,
can help?
...why this error mssg?.

**Thanks/DankU** 10^6 !!
**SFD99
San Francisco
R 4.0.4
Rstudio 1.4.1103
Ubuntu Linux 20.04 64-bit.**
