### ISSUE TITLE
Plots do not take into account whether you're plot SD when deciding on x axis

### ISSUE THREAD

**Issue by newtux** [mtennekes/tabplot#8]
Leads to weird plots when your mean is low, but SD is very high.

**Comment by mtennekes** [comment]
Could you give me a reproducible example?

**Comment by newtux** [comment]
Sorry for the delay here. Here is a minimal example. 

```
library(tabplot)

zz <- data.frame(
  a = rnorm(100000, mean = 0, sd = 1000000),
  b = rnorm(100000, mean = 0, sd = 1000000),
  c = rnorm(100000, mean = 50, sd = 10)
)
tableplot(zz)
tableplot(zz, numMode= "MB-ML")
```
![image](https://cloud.githubusercontent.com/assets/194147/21744324/3c3dccf2-d4e1-11e6-967d-d67a7c281817.png)

![image](https://cloud.githubusercontent.com/assets/194147/21744328/4376e210-d4e1-11e6-964a-4450b2f7c73a.png)


The x axis range on the 'b' plot is the same in both cases.

**Comment by mtennekes** [comment]
I thought my answer was delayed;-)
It should be fixed now! I've migrated numMode to `tableplot` (instead of `plot.tabplot`). I'll double-check it soon, and submit a new version to CRAN.
