### ISSUE TITLE
Unable to replicate examples

### ISSUE THREAD

**Issue by shwetapurushe** [mtennekes/tabplot#9]
Hello, Great work! Im trying to replicate the examples on this page https://cran.r-project.org/web/packages/tabplot/vignettes/tabplot-vignette.html. 

Unfortunately getting this error. 
"Error in dim(values) <- c(rows, cols, 1) : 
  dims [product 539400] do not match the length of object [10]".
<img width="666" alt="screen shot 2016-12-09 at 2 13 13 pm" src="https://cloud.githubusercontent.com/assets/821178/21061304/b656e87c-be19-11e6-823b-5e28d7098176.png">

**Comment by shwetapurushe** [comment]
Stupidity on my part.  With multiple analyses, I was using the tableplot function from the tableplot package. My sincere apologies.

**Comment by mtennekes** [comment]
Well, it happened to me too many times, but the other way round;-)
